literature-survey-code-jam: literature-survey-code-jam.tex
	latex literature-survey-code-jam.tex;
	latex literature-survey-code-jam.tex;	# for labels to show up
	dvips -o literature-survey-code-jam.ps literature-survey-code-jam.dvi;
	ps2pdf -dCompatibilityLevel=1.4 literature-survey-code-jam.ps
	rm -f *~ *.aux *.bbl *.blg *.dvi *.log *.out *.ps *.bak *literature-survey-code-jam.bib

